[project]
name = "nilotica"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "importlib-metadata>=8.6.1",
    "pathlib>=1.0.1",
    "pip>=25.0.1",
    "pybind11>=2.13.6",
    "pybind11-stubgen>=2.5.3",
    "setuptools>=78.1.0",
    "wheel>=0.45.1",
]
[build-system]
requires = [
    "setuptools",
    "wheel",
    "pybind11",
    "pybind11-stubgen"
]
build-backend = "setuptools.build_meta"
[tool.setuptools]
script-files = ["setup.py"]
