# 特定于开发的覆盖 (Development specific overrides)
logging:
  default_level: "DEBUG" # 开发时用更详细日志

paths:
  # 开发时可能使用不同的数据路径
  data_recording_path: "zmq_services/dev_recorded_data/"
  # 确保开发回测使用开发记录的数据 (Ensure dev backtests use dev recorded data)
  backtest_data_source_path: "zmq_services/dev_recorded_data/"

zmq_addresses:
  # 使用不同端口或 localhost 避免与生产冲突
  market_data_pub: "tcp://localhost:15555"
  market_data_rep: "tcp://localhost:12015"
  order_gateway_pub: "tcp://localhost:15557"
  order_gateway_rep: "tcp://localhost:15558"
  risk_alert_pub: "tcp://localhost:15559"

  # 回测器特定的 ZMQ 地址 (Backtester specific ZMQ addresses)
  backtest_data_pub: "tcp://localhost:15560"             # 回测行情发布地址 (Backtest market data publisher)
  backtest_order_report_pub: "tcp://localhost:15561"      # 回测订单/成交回报发布地址 (Backtest order/trade report publisher)
  backtest_order_request_pull: "tcp://localhost:15562"    # 回测订单请求接收地址 (Backtest order request PULL)

# 通用服务配置 (General service configurations)
service_settings:
  # 处理发布者队列中的消息的批量大小（例如，在 OrderExecutionGateway 中）
  # Batch size for processing messages in publisher queues (e.g., in OrderExecutionGateway)
  publish_batch_size: 1000
  recorder_batch_size: 100 # 您可以按需调整这个值